name: Run cypress on dev

# This action works with pull requests and pushes
on:
  # repository_dispatch:
  #   types: [deploy]
  workflow_dispatch:
    inputs:

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 17.8.0
      - run: npm install cypress --save-dev
      - run: npm i -D @bahmutov/cypress-extends
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run cy:run:dev